# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy
orbs:
  aws-cli: circleci/aws-cli@x.y
  serverless: circleci/serverless-framework@x.y
version: 2.1
workflows:
  deploy:
    jobs:
      - deploy

