name: Release

on:
  push:
    branches: [ master ]
    
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "ncipollo/release-action@v1"
        with:
          prerelease: false
